# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AJPCodes
email:
description: > # this means to ignore newlines until "baseurl:"
  Personal website and blog created by Allen Phelps regarding web development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://AJPCodes.github.io" # the base hostname & protocol for your site
twitter_username: AJP87
github_username:  AJPCodes
permalink: /:title

# Build settings
markdown: kramdown
